-- 0027: sync the question bank from docs/questions/*.md.
--
-- GENERATED FILE. Do not hand-edit it. Regenerate with:
--
--     node scripts/import-questions.mjs
--
-- The reviewed markdown is the source of truth.
--
-- Safe to re-run. Two things it will never do:
--
--   * It never approves a question. Everything arrives as 'draft'. Approval
--     means a CFI's name and the date written against the row — a human act.
--   * It never keeps an approval alive across a content change. 0026's
--     trigger resets any question whose words change back to draft and clears
--     its reviewer, whichever path the change arrived by.
--
-- Questions removed from the markdown are RETIRED, not deleted: a retired row
-- stops being served while the record that it existed, and any student's
-- answers to it, stay intact.
--
-- Written for the Supabase SQL Editor, which supplies the transaction.

create temp table incoming_questions (
  source_key text primary key,
  acs_code text not null,
  knowledge_area text not null,
  objective_id text,
  stem text not null,
  choice_a text not null,
  choice_b text not null,
  choice_c text not null,
  correct_choice char(1) not null,
  explanation text not null,
  figure_ref text,
  figure_supplement text,
  difficulty smallint not null,
  authored_by text,
  source_note text
);

insert into incoming_questions
  (source_key, acs_code, knowledge_area, objective_id, stem, choice_a, choice_b,
   choice_c, correct_choice, explanation, figure_ref, figure_supplement,
   difficulty, authored_by, source_note)
values
  ('PA.I.C.K1.q1', 'PA.I.C.K1', 'Aviation weather and weather services', 's1-weather-intro.metar-and-taf', 'You check the weather on a popular flight app before a cross-country. What have you actually done?', 'Satisfied the requirement to obtain a preflight weather briefing', 'Seen weather information, but not necessarily obtained it from an official source', 'Received a forecast you are entitled to rely on for your route', 'B', 'A commercial app displays weather, and it may display it well, but what makes a briefing official is the source behind it rather than the screen in front of you — some apps are qualified providers and some are not, and you are expected to know which you are using. Seeing information is not the same as getting a briefing that covers your route: an app that omits a NOTAM or an advisory has not told you what a briefing would. And nothing in a weather product entitles you to rely on it, because a forecast is a prediction rather than a promise, and the decision it informs stays yours.', null, null, 1, 'Claude (Opus 5), written from the sources named per question', 'AIM, preflight briefing sources — official versus supplemental weather information'),
  ('PA.I.C.K2b.q1', 'PA.I.C.K2b', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'A surface analysis chart shows fronts, pressure centres and station data. What is it telling you?', 'What the surface weather pattern was at a particular past time', 'What the surface pattern is forecast to be by the time you arrive', 'What conditions are along your route at your cruising altitude', 'A', 'A surface analysis is an analysis — it draws the pattern from observations already taken, and it carries the time those observations were valid. It is not a forecast, and reading it as one is how a pilot plans for weather that has already moved on; a product that predicts a future pattern is a different chart. Nor does it describe your route at altitude: it covers the surface, and it covers a broad region rather than the air you will actually be flying through.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, aviation weather services chapter — surface analysis chart'),
  ('PA.I.C.K2c.q1', 'PA.I.C.K2c', 'Aviation weather and weather services', 's1-weather-intro.metar-and-taf', 'A TAF for a nearby airport forecasts good conditions all afternoon. Your destination is a small field thirty miles away with no forecast of its own. How much does that TAF tell you?', 'It applies to any airport in the same forecast region', 'It applies exactly, because TAFs are issued by region rather than by airport', 'Less than it appears — a TAF describes the vicinity of its own airport', 'C', 'A TAF is written for one specific airport and its immediate vicinity, so conditions tens of miles away can differ; terrain, water and local effects all break the assumption that nearby means similar. Forecast regions do exist, but they are a separate and far coarser product, and a TAF is not one of them. Nor are TAFs issued regionally — they are issued airport by airport, which is exactly why a small field without one leaves you inferring from its neighbour, and inferring is not the same as being told.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, aviation weather services chapter — TAF coverage and limitations'),
  ('PA.I.C.K2d.q1', 'PA.I.C.K2d', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'What does the Graphical Forecasts for Aviation give you that a single METAR cannot?', 'Conditions across an area and across successive times, so you can see weather moving', 'A more precise account of conditions than a station observation gives', 'Enough information that you no longer need reports for individual airports', 'A', 'The value of a graphical product is the pattern: an area shown at several times running, which is how you see whether something is building, moving toward you, or clearing. Precision is the station observation''s strength instead — a graphical forecast spans a wide area and cannot be as exact about one field as an instrument sited there. And it certainly does not replace those reports: seeing the shape of the weather tells you nothing about the ceiling and visibility at the airport you intend to land at, which is the more dangerous of the two misreadings.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, aviation weather services chapter — Graphical Forecasts for Aviation'),
  ('PA.I.C.K2e.q1', 'PA.I.C.K2e', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'The winds and temperatures aloft forecast publishes figures for fixed levels, and you plan to cruise between two of them. What do you do?', 'Use the lower level, because wind is weaker closer to the ground', 'Interpolate between the two levels that bracket your altitude', 'Use whichever of the two gives the more favourable wind', 'B', 'The forecast is published at fixed levels because it has to be published at some levels, and cruising between them is the normal case — so you estimate from the two either side. There is no rule that wind weakens with height; it frequently strengthens, which is much of the reason the forecast exists at all. And choosing the more favourable of the two is not planning but wishing: a fuel calculation built on a figure you had no reason to expect is a fuel calculation that can run out.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, aviation weather services chapter — winds and temperatures aloft forecast'),
  ('PA.I.C.K2f.q1', 'PA.I.C.K2f', 'Aviation weather and weather services', 's1-weather-intro.fog-storms-icing', 'What is the practical difference between an AIRMET and a SIGMET?', 'The AIRMET covers en route weather and the SIGMET covers airport weather', 'The AIRMET is advisory and the SIGMET restricts what you are cleared to do', 'The AIRMET covers conditions hazardous particularly to light aircraft; the SIGMET, conditions hazardous to all aircraft', 'C', 'The distinction is severity and who is endangered: one warns of conditions that matter most to smaller, slower, less equipped aeroplanes, the other of weather severe enough to threaten anything flying. Neither restricts a clearance — both inform a decision that stays with the pilot, and nothing in an advisory prohibits a flight. And neither is about a single airport: both concern conditions along routes and over areas, which is what separates them from a terminal forecast.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'AIM, inflight aviation weather advisories — AIRMET and SIGMET distinction'),
  ('PA.I.C.K3a.q1', 'PA.I.C.K3a', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'You take off into smooth air beneath layered grey cloud, with steady light rain and hazy visibility. What does that combination tell you about the air?', 'It is stable', 'It is unstable', 'Stability cannot be judged from what you can see', 'A', 'Stable air resists vertical motion, and every one of those signs follows from that: cloud spreads sideways into layers instead of building upward, precipitation is steady rather than arriving in bursts, and haze stays trapped near the surface instead of being mixed away. Unstable air shows close to the opposite set — cumulus growing vertically, showers, turbulence, and often excellent visibility between the showers. And the idea that you cannot tell by looking is worth unlearning early: the sky is one of the most useful instruments you have, and an examiner will expect you to read it.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — atmospheric stability and its visible signs'),
  ('PA.I.C.K3b.q1', 'PA.I.C.K3b', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'On short final your airspeed rises sharply for a moment, then falls away, and you find yourself low. What have you most likely flown through?', 'An airspeed indication error caused by rain', 'Windshear, with a headwind that increased and was then lost', 'A gust, needing no response beyond holding your attitude', 'B', 'A gain followed by a loss is the classic shape of windshear on approach: the aeroplane meets an increasing headwind, that headwind then disappears, and the airspeed and the lift go with it, leaving you low and slow close to the ground. A gust is brief and roughly symmetric, so a sustained gain and then loss is a change in the air mass itself — and treating it as a gust is how an approach ends short of the runway. Rain does not produce that pattern either; and even were an indication suspect, the safe response that low is to go around rather than to reason about the instrument.', null, null, 3, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — low-level windshear on approach'),
  ('PA.I.C.K3b.q2', 'PA.I.C.K3b', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'Strong wind is blowing across a ridge ahead of you. Smooth lens-shaped clouds sit above the crests, with ragged cloud churning below them. Where is the worst turbulence likely to be?', 'Below and downwind of the ridge, in and near the ragged cloud', 'Inside the smooth lens-shaped clouds, which mark the strongest lift', 'Upwind of the ridge, where the air is being forced to rise', 'A', 'The ragged cloud is rotor, and rotor is the most violent part of a mountain wave — it forms beneath the wave crests on the downwind side, where the airflow has broken up. The lens-shaped cloud marks the wave itself, which is often strikingly smooth even while carrying powerful vertical currents; its hazard is the climb or descent it imposes on you, not roughness. The upwind side is generally where air rises comparatively smoothly, because the breakdown happens after the air has crossed the ridge — which is also why crossing from downwind deserves extra height.', null, null, 3, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — mountain wave and rotor turbulence'),
  ('PA.I.C.K3c.q1', 'PA.I.C.K3c', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'You fly the same local route on a still morning and again on a hot afternoon, and the afternoon flight is noticeably bumpier at the same altitude. Why?', 'The sun has heated different surfaces unevenly, setting up rising and sinking currents', 'Warmer air is denser, so it transmits gusts more strongly', 'The wind is always stronger in the afternoon', 'A', 'The ground does not warm evenly — a ploughed field, a car park and a lake all heat at different rates — and the air above each rises or sinks accordingly, so you fly through a patchwork of currents rather than a uniform mass. Warm air is in fact less dense, not more, which is the opposite of the reasoning offered and also why performance suffers on a hot day. And while afternoon wind often does freshen, the bumpiness here is convective: it appears on still days too, which is precisely what distinguishes it from wind.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — uneven surface heating and convective currents'),
  ('PA.I.C.K3d.q2', 'PA.I.C.K3d', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'What does the dewpoint tell you?', 'How much moisture that air is capable of holding', 'The temperature at which that air would become saturated if it were cooled', 'The relative humidity, expressed in degrees', 'B', 'Dewpoint is a temperature, and it names the point at which the moisture already present would be enough to saturate the air — which is what makes it useful for anticipating cloud and fog. It is not a capacity: how much moisture air can hold depends on its temperature, and the dewpoint describes what is there rather than the ceiling on it. Nor is it humidity restated, because relative humidity is a percentage comparing what is present against that capacity — two air masses at the same relative humidity can have very different dewpoints and behave quite differently.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — dewpoint as a measure of moisture'),
  ('PA.I.C.K3e.q1', 'PA.I.C.K3e', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'A cold front and a warm front pass over the same airport on different days. How do the two spells of weather typically differ?', 'The cold front brings the longer spell, because cold air moves slowly', 'They are much alike, since both are boundaries between air masses', 'The cold front brings a shorter, more violent spell; the warm front a longer spell of low cloud and poor visibility', 'C', 'A cold front undercuts warm air steeply and moves relatively quickly, so it lifts that air hard and is soon past — cumuliform cloud, showers, gusty wind, then clearing. A warm front rides up over cooler air on a shallow slope, so its cloud and precipitation stretch far ahead of it and linger. The claim that cold fronts are the slower of the two is wrong in both its conclusion and its reasoning: they generally move faster. And the two are not alike in any way that matters, because the shape of the boundary is what decides whether you face an hour of rough weather or a day of low ceilings.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — cold and warm front characteristics'),
  ('PA.I.C.K3f.q1', 'PA.I.C.K3f', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'Cumulus clouds have been building steadily taller through the middle of the day. What should you expect on the climb?', 'Turbulence, because building cumulus marks rising air in unstable conditions', 'Smooth air, because cumulus clouds are shallow', 'Icing, because cumulus clouds always hold supercooled water', 'A', 'Cumulus form means air is rising, and cumulus that keeps building means it goes on rising — so the air in and around them is in vertical motion, and you feel that as turbulence. Cumulus growing taller is by definition not shallow; their vertical development is the warning rather than a reason for comfort. And the icing claim asserts a certainty that does not hold: ice needs visible moisture and freezing temperatures together, so whether a particular cumulus threatens you depends on where its freezing level sits relative to your altitude.', null, null, 1, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — cloud form as an indicator of stability'),
  ('PA.I.C.K3.q2', 'PA.I.C.K3', 'Aviation weather and weather services', 's1-weather-intro.fog-storms-icing', 'Why is the apparently clear air beneath and downwind of a thunderstorm''s spreading anvil a poor place to fly?', 'It is acceptable, because the hazards stay inside the visible cloud', 'Hail can be thrown out of the storm and fall through air that looks clear', 'The only hazard there is reduced visibility', 'B', 'A thunderstorm''s hazards are not bounded by its cloud: hail can be carried out of the upper part of the storm and fall well clear of anything you can see, and the anvil shows you which way it is being carried. The belief that hazards stop at the cloud edge is worth losing early — turbulence, hail and severe downdraughts all reach beyond it, which is why avoidance is measured in miles rather than by clearing the visible cloud. And visibility is the least of what is present there; what is present can damage an airframe.', null, null, 3, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — thunderstorm hazards, including hail carried from the anvil'),
  ('PA.I.C.K3.q3', 'PA.I.C.K3', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'You meet turbulence rough enough to be throwing the aeroplane about. Why does slowing down help?', 'A lower speed weakens the gusts the aeroplane meets', 'A lower speed lets the autopilot hold altitude more accurately', 'At a lower speed a sharp gust stalls the wing before the structure can be overloaded', 'C', 'Slowing down works because of what happens at the limit: below a certain speed the wing reaches its stalling angle under a sharp gust and gives way, relieving the load, instead of the structure absorbing it. That speed depends on the aeroplane and its weight, which is why it is a figure to take from the flight manual rather than from memory. Nothing you do changes the air itself — your speed changes only how you meet it. And the autopilot answer misplaces the concern entirely: the reason to slow in turbulence is structural, and holding altitude precisely is not the priority in rough air.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — flight in turbulence and the reason for reducing speed'),
  ('PA.I.C.K3i.q2', 'PA.I.C.K3i', 'Aviation weather and weather services', 's1-weather-intro.fog-storms-icing', 'You are in cruise below cloud when rain begins to strike the airframe and freeze on it. What does that tell you about the air above you?', 'It is colder above, which is what froze the drops', 'There is a layer above you that is warmer than freezing', 'Nothing about the air above — freezing rain forms where it falls', 'B', 'Rain has to fall as liquid before it can freeze on contact, and it cannot have started as liquid in air below freezing — so somewhere above you there is a layer warm enough to have melted it, with colder air beneath that chilled the drops without refreezing them. That makes climbing a very different proposition from descending, which is the practical reason this matters. Assuming it is colder above gets the structure exactly backwards. And the idea that it forms where it falls misses the point: freezing rain is evidence about air you are not in, which is unusual and worth having.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — freezing rain and the temperature structure above it'),
  ('PA.I.C.K3j.q1', 'PA.I.C.K3j', 'Aviation weather and weather services', 's1-weather-intro.fog-storms-icing', 'A clear, calm night follows a damp day, and by dawn the airport is fogged in. What has most likely happened?', 'Warm moist air moved in over a cooler surface', 'A front passed through during the night', 'The ground cooled overnight and chilled the moist air resting on it to saturation', 'C', 'Clear skies let the ground radiate its heat away, calm air lets the layer just above it cool with the surface instead of being mixed, and already damp air has little cooling to do before it saturates — those three together are what produce fog by morning. Air moving in from elsewhere describes a different fog, the coastal kind, and it cannot be the answer on a calm night because it needs wind to arrive. A front is ruled out by the same evidence: it would have brought cloud and wind with it, and the night was clear and still.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — radiation fog and advection fog'),
  ('PA.I.C.K3l.q1', 'PA.I.C.K3l', 'Aviation weather and weather services', 's1-weather-intro.fog-storms-icing', 'The reported visibility at your destination is comfortable, but there is haze. In the cruise you could see a long way ahead, yet on the approach you can barely pick out the runway. Why?', 'The report must have been wrong', 'Looking down through a haze layer at a shallow angle puts far more of it between you and the runway', 'Haze affects the ground observer''s view rather than the pilot''s', 'B', 'Reported visibility is measured horizontally at the surface, while on approach you are looking through the layer at a slant — a much longer path through the haze, which is why a runway can be hard to find when the figure sounded generous. The report can be entirely accurate; it simply answers a different question from the one you are asking on final. And the last option has it inverted: the observer looking horizontally often has the better view, and the pilot descending through the layer the worse one.', null, null, 3, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — obstructions to visibility and slant range'),
  ('PA.I.C.R2b.q1', 'PA.I.C.R2b', 'Aviation weather and weather services', 's1-weather-intro.metar-and-taf', 'A forecast says your destination will stay above your personal minimums all afternoon. What is the honest way to use that?', 'As settled, since a forecast inside your minimums is what those minimums are for', 'As a prediction that can be wrong, which is why you plan an alternative anyway', 'As grounds to relax your minimums, since the margin is forecast to hold', 'B', 'A forecast states what is expected, with real uncertainty attached, so the useful question is not whether it clears your minimums but what you will do if it turns out wrong — which is what an alternative and a fuel reserve answer. Treating it as settled confuses a prediction with an observation, and a favourable forecast is exactly when a pilot is most likely to stop planning. Relaxing the minimums is the more dangerous error of the two: minimums exist to absorb forecast error, so spending them because the forecast looks good removes the margin at the moment you were relying on it.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'AIM, use and limitations of aviation weather reports and forecasts'),
  ('PA.I.C.K2a.q1', 'PA.I.C.K2a', 'Aviation weather and weather services', 's1-weather-intro.metar-and-taf', 'What does a METAR tell you?', 'Conditions forecast for an airport over a coming period', 'Conditions reported by a pilot from the air', 'Conditions that were observed at a station at a particular time', 'C', 'A METAR is an observation — what was measured, where, and when. A forecast covering a coming period at an airport is a TAF, a different product entirely, and the distinction matters because only one of the two can be wrong about the future. A report from an aircraft is a pilot report, which comes from someone flying rather than from a station on the ground, and carries all the imprecision of an eye at altitude.', null, null, 1, 'Claude (Opus 5), written from the sources named per question', 'PHAK, aviation weather services chapter — METAR versus TAF'),
  ('PA.I.C.K2a.q2', 'PA.I.C.K2a', 'Aviation weather and weather services', 's1-weather-intro.metar-and-taf', 'The wind in a written METAR and the wind a tower reads to you are referenced differently. How?', 'The written report uses true north; the spoken wind is magnetic', 'Both are magnetic, so the two always agree', 'The written report is referenced to the runway in use', 'A', 'Written reports give wind direction relative to true north, while a tower or ATIS speaks it relative to magnetic north — the same reference runways are numbered in. The two genuinely differ, which is why a runway chosen from a written report can surprise you on arrival; assuming they agree is how that surprise happens. And no weather report is referenced to a runway: working out which runway the wind favours is your job, not something the report has done for you.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'AIM, wind direction reporting — true versus magnetic reference'),
  ('PA.I.C.K3d.q1', 'PA.I.C.K3d', 'Aviation weather and weather services', 's1-weather-intro.weather-drivers', 'Through the afternoon the temperature and the dewpoint move closer together. What does that suggest?', 'The air is drying out', 'Visible moisture is becoming more likely', 'The wind is about to strengthen', 'B', 'The spread between temperature and dewpoint measures how far the air is from saturation, so a narrowing spread means it is closer to giving that moisture up as cloud, mist or fog. Reading it as drying air has the relationship backwards — it is a widening spread that indicates drier air relative to its temperature. Wind is unrelated to the spread: it comes from pressure differences, and a narrowing spread says nothing about it either way.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — temperature, dewpoint and condensation'),
  ('PA.I.C.K3i.q1', 'PA.I.C.K3i', 'Aviation weather and weather services', 's1-weather-intro.fog-storms-icing', 'What has to be present for structural ice to form on an airframe?', 'Freezing temperatures alone', 'Visible moisture alone', 'Visible moisture, and a temperature at or below freezing where the aircraft is flying', 'C', 'Structural ice needs both at once: something to freeze, and cold enough for it to freeze on the airframe — and that pairing is what makes icing forecastable rather than a surprise. Cold clear air leaves nothing to accumulate, however far below freezing it is. Cloud well above freezing wets the aeroplane instead of icing it, which is why the freezing level matters as much as the cloud does.', null, null, 2, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — structural icing conditions'),
  ('PA.I.C.K3.q1', 'PA.I.C.K3', 'Aviation weather and weather services', 's1-weather-intro.fog-storms-icing', 'Which combination is required for a thunderstorm to form?', 'Cold air, high pressure, and strong surface wind', 'Moisture, unstable air, and a lifting action', 'Rain already falling, high humidity, and darkness', 'B', 'All three ingredients have to be present: water vapour to work with, air that keeps rising once it has started, and something to start it — surface heating, terrain, or a front. Cold air under high pressure with a strong surface wind describes a clear, stable day instead, which is close to the opposite set of conditions. And rain already falling confuses a consequence with a cause: rain is something a storm produces, not something it needs in order to begin, and darkness has nothing to do with it.', null, null, 3, 'Claude (Opus 5), written from the sources named per question', 'PHAK, weather theory chapter — thunderstorm formation requirements');

-- ---------------------------------------------------------------
-- Refuse to run if a question points at an objective that does not exist. A
-- typo would otherwise import a question that can never be linked back to a
-- lesson for the student to go and read.
-- ---------------------------------------------------------------

do $check$
declare
  unknown_objectives text;
begin
  select string_agg(distinct i.objective_id, ', ' order by i.objective_id)
    into unknown_objectives
  from incoming_questions i
  where i.objective_id is not null
    and not exists (
      select 1 from public.learning_objectives o where o.id = i.objective_id
    );

  if unknown_objectives is not null then
    raise exception
      'Refusing to import: these objective ids do not exist: %. Check them against learning_objectives.',
      unknown_objectives;
  end if;
end;
$check$;

-- ---------------------------------------------------------------
-- Upsert on source_key. Content changes trip 0026's trigger, which returns
-- the row to draft and clears its reviewer.
-- ---------------------------------------------------------------

insert into public.question_bank
  (source_key, acs_code, knowledge_area, objective_id, stem, choice_a, choice_b,
   choice_c, correct_choice, explanation, figure_ref, figure_supplement,
   difficulty, authored_by, source_note, review_status)
select source_key, acs_code, knowledge_area, objective_id, stem, choice_a, choice_b,
       choice_c, correct_choice, explanation, figure_ref, figure_supplement,
       difficulty, authored_by, source_note, 'draft'
from incoming_questions
-- The predicate is repeated because 0026's unique index on source_key is
-- PARTIAL ("where source_key is not null"), and Postgres will only infer a
-- partial index for ON CONFLICT when the statement names the same condition.
-- Without it: "there is no unique or exclusion constraint matching the ON
-- CONFLICT specification".
on conflict (source_key) where source_key is not null do update set
  acs_code          = excluded.acs_code,
  knowledge_area    = excluded.knowledge_area,
  objective_id      = excluded.objective_id,
  stem              = excluded.stem,
  choice_a          = excluded.choice_a,
  choice_b          = excluded.choice_b,
  choice_c          = excluded.choice_c,
  correct_choice    = excluded.correct_choice,
  explanation       = excluded.explanation,
  figure_ref        = excluded.figure_ref,
  figure_supplement = excluded.figure_supplement,
  difficulty        = excluded.difficulty,
  authored_by       = excluded.authored_by,
  source_note       = excluded.source_note;

-- ---------------------------------------------------------------
-- Retire what the documents no longer contain. Only rows that came from this
-- pipeline: anything with no source_key was written by hand and is not ours
-- to retire.
-- ---------------------------------------------------------------

update public.question_bank q
set review_status = 'retired'
where q.source_key is not null
  and q.review_status <> 'retired'
  and not exists (
    select 1 from incoming_questions i where i.source_key = q.source_key
  );

drop table incoming_questions;

-- ---------------------------------------------------------------
-- Report. Expect 24 questions, all draft until a CFI signs them.
-- ---------------------------------------------------------------

select
  count(*) as total_questions,
  count(*) filter (where review_status = 'draft') as draft,
  count(*) filter (where review_status = 'cfi_approved') as approved,
  count(*) filter (where review_status = 'retired') as retired,
  count(distinct acs_code) as acs_codes_covered
from public.question_bank;
